### ISSUE TITLE
View downloaded images

### ISSUE THREAD

**Issue by m-hertig** [the-AjK/GT-511C3#1]
Hi, thank you for this great module. 
How can I open the downloaded .tpl files? Or how can I convert them to a current image format?

**Comment by the-AjK** [comment]
Hi,
those .tpl files are simply a raw sequence of bytes. They needs to be converted into an image file. I plan to develop it soon or later, but I dunno yet.

If you are good at programming you may try to check out the GT511-C3 SDK source code (I've just created and committed an "extra" folder), there are some snippets of code where they convert the images:

https://github.com/the-AjK/GT-511C3/tree/master/extra/GT-511C3_SDK_20130410

**Comment by m-hertig** [comment]
Thank you for the reply. I check out the snippets and see if I can make them work. However, if you plan to do this in your application, I'm very interested!

**Comment by the-AjK** [comment]
I will, for sure! Keep in touch ;)

**Comment by AdrianBalcan** [comment]
Hi,
Any update about this issue? I really need a solution for this.

**Comment by the-AjK** [comment]
Sorry, not yet.

**Comment by DEGETEL-GWARCKOL** [comment]
Hello, did you find a way to convert the image provided by the sensor into a readable bmp file ?

**Comment by the-AjK** [comment]
Hi, unfortunately my GT-511C3 hardware is not working anymore after years of 24/24 7/7 service!
I'll be looking for a replacement and maybe I will be able to continue the developing!

**Comment by DEGETEL-GWARCKOL** [comment]
Ok, thanks for your response. It looks like this guy wrote a method to implement a BMP conversion, so I'll try to start from here : http://kinoma.com/develop/documentation/projects/fingerprint-lock/
Thanks for you work anyway ;)

**Comment by the-AjK** [comment]
Thank you! Nice link tho, I will check it out! :)

**Comment by galactic-dust** [comment]
> Hi, unfortunately my GT-511C3 hardware is not working anymore after years of 24/24 7/7 service! I'll be looking for a replacement and maybe I will be able to continue the developing!

What do you mean ? The electronics has burned out ? 
Mine is still working fine, but i'm not using Nodejs anymore (the old version are not stable), i switched to C++:
https://github.com/mel-florance/gt511c3
