### ISSUE TITLE
Unable to fetch gt511c3 via npm install

### ISSUE THREAD

**Issue by sburdka** [the-AjK/GT-511C3#11]
npm http GET https://registry.npmjs.org/gt511c3

npm ERR! Error: failed to fetch from registry: gt511c3
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /home/bxxxxxx/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "node" "/usr/bin/npm" "install" "gt511c3"
npm ERR! cwd /home/bxxxxxxx
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: gt511c3
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bxxxxxxx/npm-debug.log
npm not ok

**Comment by the-AjK** [comment]
which version of node and npm do you have?

**Comment by sburdka** [comment]
npm  1.1.4 and  node  v0.6.12

**Comment by eckama11** [comment]
I am running node v0.10.29 and npm v1.4.21 and it does not work either.

**Comment by sburdka** [comment]
Solved !!!! It will works with node v0.10.46 and npm v2.15.1

**Comment by eckama11** [comment]
Did you reopen it because you didn't fix it? I still does not work for me.

**Comment by sburdka** [comment]
I didn't faced any problem after upgrading the nodejs and npm. I am using ubuntu 12.02 and compiled packages from new tarball sources not from repository.  I reopened it for you, i can't close it without problem solved at your side as well.

**Comment by sburdka** [comment]
xxxxx@ubuntu:~$ npm install gt511c3
/

> serialport@2.0.5 install /home/xxxx/node_modules/gt511c3/node_modules/serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "/home/xxxx/node_modules/gt511c3/node_modules/serialport/build/Release/node-v11-linux-x64/serialport.node" is installed via remote
gt511c3@0.1.1 node_modules/gt511c3
├── async@1.5.0
├── promise@7.0.4 (asap@2.0.4)
└── serialport@2.0.5 (bindings@1.2.1, sf@0.1.7, async@0.9.0, nan@2.0.9, debug@2.2.0, optimist@0.6.1)

It will come after successful installation.

**Comment by jesvijesvi** [comment]
What is the best and applicable version to run it with?
