### ISSUE TITLE
I have a problem with a serial communication on raspberry pi 2B.

### ISSUE THREAD

**Issue by kyeongtae** [the-AjK/GT-511C3#13]
First of all, sorry for my bad english skills.

I finished all settings. (ttyAMA0, 9600)
But, when I excute the code, 

ledON error: undefined
init err: undefined 
and so on..

Raspberry pi couldn't find all the functions in fps.
I installed serialport, but it seems like that it couldn't construct the fps object.
Do you have any solution regarding this problem?

**Comment by kyeongtae** [comment]
I just

**Comment by galactic-dust** [comment]
Hi, 
I dont know if you resolved your issue (i guess so), but i encoutered the same problem, and in fact i just inversed my two wire tx / rx, and it worked instantly  !
