### ISSUE TITLE
SerialPort initialization

### ISSUE THREAD

**Issue by Mehluko** [the-AjK/GT-511C3#14]
Hae i am new to java i'm used to python i am confused what you mean by serial port initialization?
"Open the serialport and initialize the fingerprint module"  ?

**Comment by the-AjK** [comment]
> Hae i am interested in your code for the scanner i downloaded it to use with Pi but i cant seem to make it work what i wanted to do was enroll fingerprints and verify if their are authorized. i executed the code under example and i pressed a corresponding number but it gave me an error please tell me where i went wrong i am really begging for your help please respond if yo get this. Thanks

Hi, you should show me which error you get.

**Comment by Mehluko** [comment]
this is the error i am getting

**Comment by Mehluko** [comment]
so what am i doing wrong ?   please respond if you can please

**Comment by Mehluko** [comment]
You not responding really hurts😢

Sent from my Samsung Galaxy smartphone.

-------- Original message --------
