### ISSUE TITLE
setTemplate not working

### ISSUE THREAD

**Issue by xylish7** [the-AjK/GT-511C3#15]
Hy. I'm using a GT-511C1R with a Raspberry Pi 3 Model B (also I'm new to nodejs) and i would like to retrive the templete for a specific ID so that i can insert it into an external database. So i ran the example.js and used the getTemplate function. The function worked but after it i could not run any other function, every action was returning undefined (but pressing 1 and 2 was turning on/off the led and returning an undefined), also i could not exit with 0, same error. Anyway, the tpl file was created and after i unplugged the sensor i relaunched the example.js. i deleted all id's and tryed to use the setTemplate but it returned me the same undefined. Please help me with this problem because my project depends on this. Thank you !

**Comment by linyi-xia** [comment]
Would you mind put a few screenshots here?

**Comment by linyi-xia** [comment]
I saw your screenshots.  
in /lib/gt511c3.js 
line 946-948 should be like this, which is the most recent version: 
`        function(err) {
          reject('send command: ' + err);
        });
`
I had undefined error too, with the way it is. 
Please change line 943 and 947 to:

`         reject(err);`

You should see the actual error now. I got "the specified ID is already used". Basically, you can't overload it. 

I haven't tried the stuff below yet, but I think this should get you started:
in /examples/example.js look for `var ID_TO_USE = 199;`
Change the ID to something else, between 0-199. I'm assuming you can't enroll it first then try to setTemplate. I'm not sure what else you are trying to do, but try changing the ID to an empty one. Also, make sure you have a template file ready, in the naming convention of template_xxx.tpl

**Comment by xylish7** [comment]
Thank you! :) I will try this. At this moment I&#39;m not at home so i cant try it but i will make the changes. My problem is that the fingerprint can enroll only 20 in my case or 200 for GT511C3. Anyway i would like to enorll as many fingerprints as i want so for that i use an external database so i can store the templates there and get them whenever i want. Thank you for being so fast :) Hope it works!

Have a nice day!

**Comment by xylish7** [comment]
I was able to resolve the problem. The problem was the data sheet from sparkfun. They say you need to have a template (of the fingerprint) of 498 bytes but the problem is that it is actually 506. So after I modified the templete size to the correct one eveything works fine now.

**Comment by drapizaaldryx** [comment]
how did you modify the template size? what command did you use?
