### ISSUE TITLE
Errors installing

### ISSUE THREAD

**Issue by cmenchion** [the-AjK/GT-511C3#18]
I'm having issues with installing. this is my error 

> pi@raspberrypi:~ $ sudo npm install gt511c3

> serialport@2.0.5 install /home/pi/node_modules/serialport
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.8.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/node_modules/serialport/.node-gyp"
make: Entering directory '/home/pi/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/7.8.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/pi/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.34-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/node_modules/serialport/build/Release/node-v51-linux-arm/serialport.node" "--module_name=serialport" "--module_path=/home/pi/node_modules/serialport/build/Release/node-v51-linux-arm"
gyp ERR! cwd /home/pi/node_modules/serialport
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/node_modules/serialport/build/Release/node-v51-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/node_modules/serialport/build/Release/node-v51-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.34-v7+
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/pi/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/node_modules/serialport
node-pre-gyp ERR! node -v v7.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.13
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/node_modules/serialport/build/Release/node-v51-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/node_modules/serialport/build/Release/node-v51-linux-arm' (1)
/home/pi
├── async@1.5.0 
└─┬ promise@7.0.4 
  └── asap@2.0.5 

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm WARN In serialport@2.0.5 replacing bundled version of node-pre-gyp-github with node-pre-gyp-github@1.0.5
npm ERR! Linux 4.4.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "gt511c3"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! serialport@2.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@2.0.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-04-02T12_32_27_310Z-debug.log

> 

Could this be as simple as permissions?

**Comment by SuperCipher** [comment]
are you sure you use the right version of node.js
Try [https://www.raspberrypi.org/forums/viewtopic.php?f=34&t=102737](url)

**Comment by cmenchion** [comment]
Not sure, I don't see anything in his docs that start way version to use but I have to use v6.x because of another project for my laser. What am I supposed to see in that link? I skimmed it but not sure the relevance.

Seems line my issue is permissions or the serial version which if I try any other version manual install it gives 404.

**Comment by SuperCipher** [comment]
@cmenchion 

<img width="841" alt="screen shot 2560-04-04 at 22 52 58" src="https://cloud.githubusercontent.com/assets/6429197/24666169/bc6f3450-1989-11e7-846e-fe4adb5be9e7.png">

This is an error I got from install node version 7. by apt-get.

but after install version 
<img width="539" alt="screen shot 2560-04-05 at 00 09 40" src="https://cloud.githubusercontent.com/assets/6429197/24669357/52029c1e-1994-11e7-9fa9-a44e36fd4357.png">

every thing work fine

you might want to try install node  according to this  [http://weworkweplay.com/play/raspberry-pi-nodejs/](url)

orelse use the python library and Python function from NodeJS.

**Comment by SuperCipher** [comment]
oh!! I remember now I used to have similar problem when installing similar to this
try [https://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo](url)

> install without sudo

PS. I quite a newbie so take me with a grain of salt, I thought I used to have the same problem like you and want to be helpful with someone who might be in the same shoe as I were.

**Comment by cmenchion** [comment]
This is a great help. Next chance I get I'll try that version. I appreciate your help(I'm also a newbie) I'll post back when i can!! Thank you!

**Comment by SuperCipher** [comment]
For anyone who has this problem I have reproduced the error and solved it by reinstall node to ARM-version of Node 4.2.1 

>  tutorial to install ARM-version NodeJS
[http://weworkweplay.com/play/raspberry-pi-nodejs/](url)
_don't forgot to reboot after install_
