### ISSUE TITLE
init err: undefined

### ISSUE THREAD

**Issue by kim-minahm** [the-AjK/GT-511C3#19]
First off thanks for all the work you put into here.

I am trying to get this to work with a raspberry pi 3 B with node version 4.2.1 and npm 2.14.7
When I run the example code I am getting an error
`init err: undefined`
I console logged the error and am getting the message 
`didnt match any baudrate!`
Not quite sure where to go with this

**Comment by SuperCipher** [comment]
@kimminahm 
Have you try configuring the GPIO Serial Port On Raspbian yet.

**Comment by SuperCipher** [comment]
was it look like this
@kimminahm 
<img width="487" alt="screen shot 2560-04-09 at 17 27 10" src="https://cloud.githubusercontent.com/assets/6429197/24836591/d97fb1d2-1d49-11e7-9583-021ae44512f8.png">

**Comment by ayushgargdroid** [comment]
I am facing the same problem. I had used the example.js code in this repo. It gives the following log:
`init err: undefined`
`didnt match any baudrate!`

@SuperCipher Serial Ports have been configured on my RPi .
I am using Raspberry Pi 3.

node -v 
v4.2.1
npm -v
v2.14.7

**Comment by SuperCipher** [comment]
hi @ayushgargdroid 
I used R Pi3 and node v4.2.1 too

This error can cause by many things.
Have you ever get the GT-511C3 module to work with python library before? so I can assume that you have done the most of the stuff right.

If not, I recommend you to try this library first.

- http://makesensors.botbook.com/code.html

> PS. I used to stuck at this error for months. I just want to tell you that I have been there and hopefully, we will get through this together.
