### ISSUE TITLE
Identify always return me 0

### ISSUE THREAD

**Issue by JordiSapesPlanas** [the-AjK/GT-511C3#2]
Hi, congratulations for this module!!
I'm trying to identify a finger but always ID is 0. The code is  the next:  

```
fingerPrintSensor.ledONOFF(fingerPrintSensor.LED_ON);
fingerPrintSensor.waitFinger(10000)
    .then(fingerPrintSensor.captureFinger(0))
    .then(function() {
        return fingerPrintSensor.identify();
    }, function(err){console.log(err)})
    .then(function (ID){
        console.log("identify: ID = " + ID);
    }, function(err){console.log(err)}).done();
```

Also it returns me 0 when I put a finger print that is not in database. 

Why I have this issue? 

Lots of thanks

Why I have this issue? 

Lots of thanks

**Comment by the-AjK** [comment]
Hi,

may you give me more informations about the context?
- does the init procedure completed successfully?
- does the enrollment procedure finished succesfully?
- does the led switched on correctly?

as next can you try to capture a finger that is already placed on the fingerprint module?
You should switch on the led, place a finger on the fingerprint module and manually call this procedure:

``` js
fps.captureFinger(0)
.then(function() {
    return fps.identify();
})
.then(function(ID) {
    console.log("identify: ID = " + ID);
}, function(err) {
    console.log("identify err: " + fps.decodeError(err));
});
```

As last try, I would suggest you to clear every fingerprint stored inside the module with a "deleteAll" command:

``` js
fps.deleteAll().then(function() {
    console.log('deleteAll: OK!');
}, function(err) {
    console.log('deleteAll err: ' + fps.decodeError(err));
});
```

and then try a new enrollment procedure.

Let me know!

JK

**Comment by JordiSapesPlanas** [comment]
Hi,
Fps has init successful and I have enrollment successful. When I delete the database it deletes okay, and it doesn't show me any error. I have tried your code example and it continues identifying always ID with value 0. The unique difference is that I use FingerPrint 511C1R, but the protocol is the same. The difference is the capacity of storage. I don't understand why it returns me always 0...

Thank you

**Comment by the-AjK** [comment]
It's weird!
I've just checked the 511C1R datasheet (https://cdn.sparkfun.com/datasheets/Sensors/Biometric/GT-511C1R_datasheet_V1%205_20140312.pdf) and the protocol seems the same yes.

Actually i'm using this module with my 511C3 and it works fine. hmm

Can you set the debug flag true and post the console log? Maybe we can investigate further.

``` js
var fps = new GT511C3('/dev/ttyS1', {
    baudrate: 115200
    debug: true
});
```

**Comment by JordiSapesPlanas** [comment]
Hi! 
Using the debug flag (working with default baudrate 9600) the output is the next

sending 55aa01000100000012001301 [12 bytes]...
sending 55aa01000000000060006001 [12 bytes]...
command sent!
got a response[CRC][ACK] params: 0
command sent!
sending 55aa01000000000051005101 [12 bytes]...
command sent!
got a response[CRC][ACK] params: 0
identify: ID = 0
got a response[CRC][ACK] params: 1

I think the problem is that I'm receiving 2 ack and I always return the first with value 0( I tested few times and always I obtain same debug) but the correct ack is with params 1 .

Now I will try with baudrate 115200

**Comment by the-AjK** [comment]
I see, 
it may be a  concurrency bug. I will try to solve it as soon as i will have some free time!

Let me know if you get the same problem with higher speeds.

**Comment by JordiSapesPlanas** [comment]
I have solved  the problem!! It wasn't a problem with speed, the problem it was by the cables.  One of them isn't do good contact! Last week I ordered a new connector and it works perfectly! Great Job in your module for node!! 

I have an other issue but is not software issue. If somoene can help me it will be fantastic. I have been executing your module in Rasberry Pi B+ and it runs okay, but i would like to debug my code and test it with my PC. I have a FTDI Breakout from sparkfun, but fedora and ubuntu didn't detect it... Do you know how to install drivers or some solution for test in my linux?

**Comment by the-AjK** [comment]
Good news! 
About your problems with the FTDI drivers I may suggest you to google about it, there should be tons of online tutorials.
Have a nice day!
