### ISSUE TITLE
getting error when use npm install gt511c3

### ISSUE THREAD

**Issue by subhashsoni99** [the-AjK/GT-511C3#20]
D:\node\fingureprint>npm install gt511c3

> serialport@2.0.5 install D:\node\node_modules\serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'D:\\node\\node_modules\\serialport\\node_modules\\node-
pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.13
node-pre-gyp info using node@8.1.4 | win32 | ia32
node-pre-gyp verb command install []
node-pre-gyp info check checked for "D:\node\node_modules\serialport\build\Relea
se\node-v57-win32-ia32\serialport.node" (not found)
node-pre-gyp http GET https://github.com/voodootikigod/node-serialport/releases/
download/2.0.5/node-v57-win32-ia32.tar.gz
node-pre-gyp http 404 https://github.com/voodootikigod/node-serialport/releases/
download/2.0.5/node-v57-win32-ia32.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for htt
ps://github.com/voodootikigod/node-serialport/releases/download/2.0.5/node-v57-w
in32-ia32.tar.gz (falling back to source compile with node-gyp)
node-pre-gyp verb command build [ 'rebuild' ]

D:\node\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Pro
gram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp
\bin\node-gyp.js" clean )  else (node "" clean )

D:\node\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Pro
gram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp
\bin\node-gyp.js" configure --fallback-to-build --module=D:\node\node_modules\se
rialport\build\Release\node-v57-win32-ia32\serialport.node --module_name=serialp
ort --module_path=D:\node\node_modules\serialport\build\Release\node-v57-win32-i
a32 )  else (node "" configure --fallback-to-build --module=D:\node\node_modules
\serialport\build\Release\node-v57-win32-ia32\serialport.node --module_name=seri
alport --module_path=D:\node\node_modules\serialport\build\Release\node-v57-win3
2-ia32 )

D:\node\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Pro
gram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp
\bin\node-gyp.js" build --fallback-to-build --module=D:\node\node_modules\serial
port\build\Release\node-v57-win32-ia32\serialport.node --module_name=serialport
--module_path=D:\node\node_modules\serialport\build\Release\node-v57-win32-ia32
)  else (node "" build --fallback-to-build --module=D:\node\node_modules\serialp
ort\build\Release\node-v57-win32-ia32\serialport.node --module_name=serialport -
-module_path=D:\node\node_modules\serialport\build\Release\node-v57-win32-ia32 )

D:\node\node_modules\serialport\build\binding.sln : error MSB3411: Could not lo
ad the Visual C++ component "VCBuild.exe". If the component is not installed, e
ither 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Fra
mework 3.5, or 2) install Microsoft Visual Studio 2008.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:197:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallb
ack-to-build" "--module=D:\\node\\node_modules\\serialport\\build\\Release\\node
-v57-win32-ia32\\serialport.node" "--module_name=serialport" "--module_path=D:\\
node\\node_modules\\serialport\\build\\Release\\node-v57-win32-ia32"
gyp ERR! cwd D:\node\node_modules\serialport
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=D:\node\node_modules\serialport\build\Release\node-v57-win32-i
a32\serialport.node --module_name=serialport --module_path=D:\node\node_modules\
serialport\build\Release\node-v57-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\node\node_modules\se
rialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:208:5)
node-pre-gyp ERR! System Windows_NT 6.1.7600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\node\\node_
modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "-
-fallback-to-build"
node-pre-gyp ERR! cwd D:\node\node_modules\serialport
node-pre-gyp ERR! node -v v8.1.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.13
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\node\node_
modules\serialport\build\Release\node-v57-win32-ia32\serialport.node --module_na
me=serialport --module_path=D:\node\node_modules\serialport\build\Release\node-v
57-win32-ia32' (1)
npm WARN enoent ENOENT: no such file or directory, open 'D:\node\package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.
npm WARN serialport@2.0.5 had bundled packages that do not match the required ve
rsion(s). They have been replaced with non-bundled versions.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@2.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@2.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\India\AppData\Roaming\npm-cache\_logs\2017-07-18T05_13_47_
800Z-debug.log

D:\node\fingureprint>

**Comment by subhashsoni99** [comment]
not able to change serialport latest version from json

**Comment by Bjeurn2** [comment]
Dear AjK, 
1. Thank you very much for the extensive work you did on the Javascript code for the GT-511C3 FPS.
2. I run into the same problem as subhashsoni99 when trying to run the code on my Raspberry Pi 3 + B (Node v8.16.1 and npm v6.4.1).
3. Additionally, when I test-run the code on RunKit, it gives: Cannot find module '/app/available_modules/1568039807000/gt511c3/node_modules/serialport/build/Release/node-v57-linux-x64/serialport.node'
4. I am very new to coding and Javascript and have been trying for 2 days to find a solution, but sofar have been not very successful.
5. Can you perhaps give me a clue of where to look?
Thank you
