### ISSUE TITLE
gt511c3 led timeout

### ISSUE THREAD

**Issue by shahrzadNazemi** [the-AjK/GT-511C3#22]
the module wont work after some time and i found out that its because its led gives an error named timeout.what should i do?

**Comment by shahrzadNazemi** [comment]
@the-AjK  please help me....

**Comment by galactic-dust** [comment]
If you're interested i developed an alternative with C++, but it doesn't work out of the box and it's not maintained anymore.
But maybe it can help you figure it out:
https://github.com/mel-florance/gt511c3
