### ISSUE TITLE
Not installing from Github...

### ISSUE THREAD

**Issue by osamasabir** [the-AjK/GT-511C3#23]
![image](https://user-images.githubusercontent.com/17942396/46825229-90127d80-cdac-11e8-9eb0-10c7a0b00150.png)

why it not installing ?? anyone help me out ???

**Comment by galactic-dust** [comment]
Hello,

I think you just need to install git on the host machine. Can you retry with a git for windows installed ?

**Comment by osamasabir** [comment]
> Hello,
> 
> I think you just need to install git on the host machine. Can you retry with a git for windows installed ?

sorry my mistake, but now it is installed.. now the errors are more....


![image](https://user-images.githubusercontent.com/17942396/46826540-acfc8000-cdaf-11e8-8208-7aa4a83d0d38.png)

**Comment by the-AjK** [comment]
@osamasabir can't you notice the four red lines of error explaination?
It gives you also suggestions how to fix it.
