### ISSUE TITLE
turn led on

### ISSUE THREAD

**Issue by beckmx** [the-AjK/GT-511C3#3]
Hello, this is a great module, but I have problems setting the led on, do you happen to have the example for that?

Greetings!

**Comment by the-AjK** [comment]
Hi, 
yes, you may check out the readMe: https://github.com/the-AjK/GT-511C3/blob/master/README.md

The module must be initialized before executing this command:

``` js
fps.ledONOFF(fps.LED_ON);
```

Here an example:

``` js
var GT511C3 = require('gt511c3');

var fps = new GT511C3('/dev/ttyS1');

fps.init().then(
    function() {
        //init ok
        console.log('firmware version: ' + fps.firmwareVersion);
        console.log('iso area max: ' + fps.isoAreaMaxSize);
        console.log('device serial number: ' + fps.deviceSerialNumber);
        fps.ledONOFF(fps.LED_ON);
    },
    function(err) {
        console.log('init err: ' + err);
    }
);
```

**Comment by beckmx** [comment]
got it, I saw also your example, cool!

2015-09-15 2:53 GMT-05:00 Alberto Garbui notifications@github.com:

**Comment by the-AjK** [comment]
Thanks! ;)
