### ISSUE TITLE
isPressFinger gets pressed by itself

### ISSUE THREAD

**Issue by beckmx** [the-AjK/GT-511C3#4]
I tried to detect whenever someone presses the module but it looks the function gets fired even if no finger is positioned, the same happens with the waitFinger.

``` js
var GT511C3 = require('gt511c3');
var fps = new GT511C3('/dev/tty.usbserial-A800K5UT');
console.log('starting now');
fps.init().then(
    function() {
        //init ok 
        fps.ledONOFF(1);
        fps.waitFinger(8000).then(function() {
            console.log('waitFinger: pressed!');
        }, function(err) {
            console.log('waitFinger err: ' + fps.decodeError(err));
        });


    },
    function(err) {
        console.log('init err: ' + err);
    }
);
```

**Comment by the-AjK** [comment]
The "isPressFinger" method checks if a finger is placed on the sensor module in real time.
In your case, if you want to detect whenever someone put a finger on the module, the correct method is waitFinger() with a correct timeout in ms.

Your code seems correct, but I would suggest to add a time delay after the "ledONOFF" command to let the module to fully switch ON the led before executing the waitFinger command.

In any case, write down any error code you get. It may be helpful.

**Comment by beckmx** [comment]
it looks the async import is a most, after putting the async, it now works fine,  using the example file I want to get the getRawImage data but it is not returning any data, these are the debug messages

init GT511-C3 at 9600 baud...
sending 55aa01000100000001000201 [12 bytes]...
command sent!
got a response[CRC][ACK] params: 0
data[CRC][24]:# ��@�c�Tgs%.
init: OK!
firmware version: 20141223
iso area max: 0
device serial number: ef13ef4014c86388546773252e000000
sending 55aa01000100000012001301 [12 bytes]...
command sent!
got a response[CRC][ACK] params: 0
ledON: OK!
sending 55aa01000000000063006301 [12 bytes]...
command sent!
got a response[CRC][ACK] params: 0
getRawImage ACK!
getRawImage err: undefined

**Comment by beckmx** [comment]
the timeout for the fingerpress is working fine, but the capture image still not getting it to work, any suggestions?

**Comment by the-AjK** [comment]
Hi, 
seems that the getRawImage command get a successfull acknowledge, but something is wrong while retrieving the 19200bytes of rawImage.
What about the getImage command?

**Comment by beckmx** [comment]
Yeah it makes the same thing, I believe it might be a problem with the firmware itself, I already contacted the manufacturer, because even using their demo app, it cannot pull images, what firmware version do you have?

**Comment by the-AjK** [comment]
My firmware version is: 20121215. If that's a date, then you should have a more recent version.
Do you have any newer datasheet version rather than 1.1?

**Comment by beckmx** [comment]
well, yeah definately is the SDK version, because in some videos I have
seen previous versions working fine, mine es 20141223, I would like to
reinstall a firmware but there is not enough information about it.

2015-09-21 10:46 GMT-05:00 Alberto Garbui notifications@github.com:

**Comment by linyi-xia** [comment]
i had the same problem. The problem is essentially that we isPressFinger executed first before set LED on. I used the library and did a back to back of turning the LED on and isPressfinger. All I did was to add a setTimeout() with 200ms to wait for the LED and then isPressfinger works perfectly.

**Comment by beckmx** [comment]
did you manage to get live image working?

2015-10-16 18:30 GMT-05:00 cheatcodex notifications@github.com:

**Comment by linyi-xia** [comment]
I wasn't trying to get a live image. All i need is a ID back from the identification. I was trying to use the python library before and ran into the same issue. I put the RX and TX line on a scope and looked at it. Timing was the problem at least for the python library. I didn't look into my debug messages. Just from my past experience with the other library, I added the delay. 
turn on the LED then
setTimeout (function(){
    fps.isPressFinger().then(function(){
         console.log("Finger Pressed")
    },function(err){
         console.log(fps.decodeError(err));
    });
},200);

**Comment by beckmx** [comment]
I did get the pressFinger working correctly but then when trying to make
the live image working, it really seems a faulty firmware, the module
itself just stops

2015-10-16 19:24 GMT-05:00 cheatcodex notifications@github.com:

**Comment by linyi-xia** [comment]
I tried the example.js with command d. It seems to work for me. Trying to attach a screenshot of what I have. 
![capture2](https://cloud.githubusercontent.com/assets/9066359/10619450/9618fdca-772a-11e5-9e1b-f129ca57cd2f.PNG)

**Comment by beckmx** [comment]
what firmware version do you have?

2015-10-20 15:01 GMT-05:00 cheatcodex notifications@github.com:

**Comment by linyi-xia** [comment]
20150120 i think.

**Comment by beckmx** [comment]
mine is 20141223, where and when did you bought it? just in case I want the
same too

2015-10-21 12:25 GMT-05:00 cheatcodex notifications@github.com:

**Comment by linyi-xia** [comment]
SparkFun i think. I got the gt-511c3 just because the operating voltages. Got it this July or August, sometime in the past summer.
