### ISSUE TITLE
Question regarding writeSync

### ISSUE THREAD

**Issue by linyi-xia** [the-AjK/GT-511C3#5]
In example.js line 218:
                rele3.writeSync(0);
                setTimeout(function() {
                    rele3.writeSync(1);
                }, 1000);

I'm not sure what this section of code does. Can someone give me a hint? Where I'm even writing this to? Also, why it's low and then high? 

Thanks!

**Comment by the-AjK** [comment]
Sorry, that was a piece of code that I've used during my tests to switch on a relay and then switch it  off after 1000ms.
You don't need it.

I've removed those lines from the example.js

Thanks!

**Comment by linyi-xia** [comment]
Thanks!
