### ISSUE TITLE
Issues installing it on Raspberry Pi 2

### ISSUE THREAD

**Issue by jownsftw** [the-AjK/GT-511C3#6]
Hi,

I'm having an issue installing it on my pi 2. It keeps failing with this error. Does anyone have any advice regarding this? It seems like it's an issue for raspberry pi 2. 
## pi@raspberrypi /usr/local/bin $ sudo npm install gt511c3

> serialport@1.6.3 install /usr/local/bin/node_modules/gt511c3/node_modules/serialport
> node-pre-gyp install --fallback-to-build

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/iojs-3.3.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/bin/node_modules/gt511c3/node_modules/serialport/.node-gyp"
make: Entering directory '/usr/local/bin/node_modules/gt511c3/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:80,
                 from ../src/serialport.h:5,
                 from ../src/serialport.cpp:3:
../node_modules/nan/nan_implementation_12_inl.h: In static member function 'static NanIntern::FactoryBasev8::Signature::return_t NanIntern::Factoryv8::Signature::New(NanIntern::Factoryv8::Signature::FTH, int, NanIntern::Factoryv8::Signature::FTH_)':
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to 'v8::Signature::New(v8::Isolate_, NanIntern::Factoryv8::Signature::FTH&, int&, NanIntern::Factoryv8::Signature::FTH_&)'
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from /usr/local/bin/node_modules/gt511c3/node_modules/serialport/.node-gyp/iojs-3.3.1/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/serialport.h:5,
                 from ../src/serialport.cpp:3:
/usr/local/bin/node_modules/gt511c3/node_modules/serialport/.node-gyp/iojs-3.3.1/include/node/v8.h:4450:27: note: static v8::Localv8::Signature v8::Signature::New(v8::Isolate_, v8::Handlev8::FunctionTemplate)
   static Local<Signature> New(
                           ^
/usr/local/bin/node_modules/gt511c3/node_modules/serialport/.node-gyp/iojs-3.3.1/include/node/v8.h:4450:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/serialport.h:5:0,
                 from ../src/serialport.cpp:3:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:171:25: error: redefinition of 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)'
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:166:25: note: 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)' previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:564:13: error: 'node::smalloc' has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:564:35: error: expected ',' or '...' before 'callback'
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function 'v8::Localv8::Object NanNewBufferHandle(char_, size_t, int)':
../node_modules/nan/nan.h:568:50: error: 'callback' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:568:60: error: 'hint' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function 'v8::Localv8::Object NanNewBufferHandle(const char_, uint32_t)':
../node_modules/nan/nan.h:575:67: error: call of overloaded 'New(v8::Isolate_, const char_&, uint32_t&)' is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:575:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/serialport.h:5,
                 from ../src/serialport.cpp:3:
/usr/local/bin/node_modules/gt511c3/node_modules/serialport/.node-gyp/iojs-3.3.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, v8::Handlev8::String, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                        ^
/usr/local/bin/node_modules/gt511c3/node_modules/serialport/.node-gyp/iojs-3.3.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from 'uint32_t {aka unsigned int}' to 'node::encoding'
/usr/local/bin/node_modules/gt511c3/node_modules/serialport/.node-gyp/iojs-3.3.1/include/node/node_buffer.h:43:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                        ^
/usr/local/bin/node_modules/gt511c3/node_modules/serialport/.node-gyp/iojs-3.3.1/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from 'const char_' to 'char_'
In file included from ../src/serialport.h:5:0,
                 from ../src/serialport.cpp:3:
../node_modules/nan/nan.h: In function 'v8::Localv8::Object NanNewBufferHandle(uint32_t)':
../node_modules/nan/nan.h:579:61: error: could not convert 'node::Buffer::New(v8::Isolate::GetCurrent(), size)' from 'v8::MaybeLocalv8::Object' to 'v8::Localv8::Object'
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function 'v8::Localv8::Object NanBufferUse(char_, uint32_t)':
../node_modules/nan/nan.h:586:12: error: 'Use' is not a member of 'node::Buffer'
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
serialport.target.mk:90: recipe for target 'Release/obj.target/serialport/src/serialport.o' failed
make: *_\* [Release/obj.target/serialport/src/serialport.o] Error 1
make: Leaving directory '/usr/local/bin/node_modules/gt511c3/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/bin/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/bin/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=serialport" "--configuration=Release" "--module_name=serialport" "--version=1.6.3" "--major=1" "--minor=6" "--patch=3" "--runtime=node" "--node_abi=node-v45" "--platform=linux" "--target_platform=linux" "--arch=arm" "--target_arch=arm" "--module_main=./serialport" "--host=https://node-serialport.s3.amazonaws.com/" "--module_path=/usr/local/bin/node_modules/gt511c3/node_modules/serialport/build/serialport/v1.6.3/Release/node-v45-linux-arm" "--remote_path=./serialport/v1.6.3/Release/" "--package_name=node-v45-linux-arm.tar.gz" "--staged_tarball=build/stage/serialport/v1.6.3/Release/node-v45-linux-arm.tar.gz" "--hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/" "--hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/node-v45-linux-arm.tar.gz"
gyp ERR! cwd /usr/local/bin/node_modules/gt511c3/node_modules/serialport
gyp ERR! node -v v3.3.1
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/iojs rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.6.3 --major=1 --minor=6 --patch=3 --runtime=node --node_abi=node-v45 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/usr/local/bin/node_modules/gt511c3/node_modules/serialport/build/serialport/v1.6.3/Release/node-v45-linux-arm --remote_path=./serialport/v1.6.3/Release/ --package_name=node-v45-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.6.3/Release/node-v45-linux-arm.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/node-v45-linux-arm.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/bin/node_modules/gt511c3/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:764:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.1.13-v7+
node-pre-gyp ERR! command "/usr/local/bin/iojs" "/usr/local/bin/node_modules/gt511c3/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/bin/node_modules/gt511c3/node_modules/serialport
node-pre-gyp ERR! node -v v3.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/iojs rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.6.3 --major=1 --minor=6 --patch=3 --runtime=node --node_abi=node-v45 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/usr/local/bin/node_modules/gt511c3/node_modules/serialport/build/serialport/v1.6.3/Release/node-v45-linux-arm --remote_path=./serialport/v1.6.3/Release/ --package_name=node-v45-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.6.3/Release/node-v45-linux-arm.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/node-v45-linux-arm.tar.gz' (1)
npm ERR! Linux 4.1.13-v7+
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "gt511c3"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! serialport@1.6.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.6.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

**Comment by the-AjK** [comment]
Hi, I will install it on my own raspberryPi2 asap.

Meanwhile you may try to upgrade the serialport module to the last version with:

``` js
cd <project folder>/node_modules/gt511c3
npm install serialport@2.0.5 --save
```

**Comment by the-AjK** [comment]
Solved. Checkout the last release.
