### ISSUE TITLE
Will work with GT-511C1R and raspberrypi2? 

### ISSUE THREAD

**Issue by deep4U** [the-AjK/GT-511C3#7]
Hi
As this is for GT511C3 and I have GT511C1R module I am confused little bit.
I do know that both are very similar and have used arduino library of GT511C3 on the same
But unsure about image upload/download implementation of bot as Arduino library does not support 
Also I want to use it with raspberry pi 2 and PL2303HX USB to ttl so that I can easily connect both 
Raspberry pi 2 USB port :-> ttl :-> GT511C1R
I will have a serial port through this converter which I can use.But still want to ensure that It should work.
Also do I need potential divider between the ttl and FPS module same as arduino interfacing
I should be able to do everything image upload/download authentication identification enrolling etc
Thanks

**Comment by the-AjK** [comment]
Hi, 
the GT511C1R should be 100% compatible with GT511C3. There is only less fingerprints' memory in the GT511C1R.

The Raspberry Pi2 have a built in serial port:

TxD is on pin 8, GPIO14 (serial output 3V3 logic)
RxD is on pin 10, GPIO15 (serial input 3V3 logic)

You may use this serial port rather than the PL2303HX usb module, you just have to care about the raspberryPi2 RX line which is 3.3V. I mean that you have to use a limit resistor between the FPS TX line (5V) and the Pi2 RX line (3.3V).

The last (and best) option is to use a "logic level converter" between the raspberry serial port and the FPS module. (here an example: https://www.sparkfun.com/products/12009 )

**Comment by deep4U** [comment]
potential devider will also do it right?
also I should be able to do everything image upload/download authentication identification enrolling etc
Will update once I get jst sh connector as I lost mine 
Thanks

**Comment by the-AjK** [comment]
Yeah, a potential divider / voltage divider will do the job.

The image download functionality is still under development, anyway all the other operations are available. Check out the README file.

Have a nice day!

**Comment by deep4U** [comment]
but can I upload images on the fly?
In the sense record and send images of people who make attempt to open it to host pc(rpi2)....

**Comment by deep4U** [comment]
one more thing can I call the functions from c code somehow?

**Comment by the-AjK** [comment]
actually its possible to get the buffer sequence of bytes with the commands getImage() and getRawImage(). You will have to decode it to a valid image format yourself.

About calling the function from c code, I don't know if exist something like a node wrapper. Dunno...

**Comment by deep4U** [comment]
ok do u know any tool to convert those images ?

**Comment by deep4U** [comment]
I Know m troubling a lot but just curious

**Comment by the-AjK** [comment]
actually no. I've planned to develop a function to export directly a bitmap image.

**Comment by deep4U** [comment]
ok I will be looking forward to that function for sure thank u alot
Amazing work 
Was going to code it myself in c for raspberry pi 2 than I found this 
cheers

**Comment by deep4U** [comment]
one sec the fps is also a 3.3 logic level ttl uart device 
than why do I Need a resistor?

**Comment by deep4U** [comment]
I am trying to get the raspberry pi 2 talk to fps 
meanwhile I have a request
I am using GT511C1R which has only 19 fingerprints
to make the code easily portable to C1 and C3 can we have a constant with value as 199  /  200
so that no one has to change 199 to 19 and 200 to 20 in entire code ?
one has to change just value of the constant?

**Comment by dobri95** [comment]
@
